### ISSUE TITLE
Non-blocking display API affects wrong LEDs

### ISSUE THREAD

**Issue by br0kenpixel** [nrf-rs/microbit#108]
Hi. I've been experimenting with the non-blocking display API and noticed that in some cases the wrong LEDs are being affected.
For example, if I take the examples/display-nonblocking example and change the `heart_image` function to display a smiley face instead:
```rust
fn heart_image(inner_brightness: u8) -> GreyscaleImage {
    let b = inner_brightness;
    GreyscaleImage::new(&[
        [0, 0, 0, 0, 0],
        [0, b, 0, b, 0],
        [0, 0, 0, 0, 0],
        [b, 0, 0, 0, b],
        [0, b, b, b, 0],
    ])
}
```
The 4th and 14th LED (the ones above and below the right eye) are also turning on, although very faintly. If I try to display the same image using the blocking API, it looks fine.

> Micro:Bit version: 2.1

**Comment by mattheww** [comment]
I can reproduce this behaviour with a debug build, but it's OK in a release build.

Perhaps the debug build isn't running fast enough to get all the work done before the next interrupt comes in.

**Comment by mattheww** [comment]
I've had a look and I don't see why a dropped interrupt would lead to this symptom.

**Comment by mattheww** [comment]
I think I see the cause: on the micro:bit v2 the GPIO pins are on two ports, and we weren't being careful enough about the order of writes to make sure that intermediate states don't cause unwanted LEDs to be lit.

**Comment by mattheww** [comment]
I had a quick look at the blocking code. That writes pins individually rather than using `OUTSET` and `OUTCLR`.

The order it uses looks safe to me: it explicitly sets all columns 'dark' after it's finished displaying a row, then sets the new row 'light', then starts setting columns 'light'.
