### ISSUE TITLE
is here a example for Radio?

### ISSUE THREAD

**Issue by bestony** [nrf-rs/microbit#15]
I read the exmples directory , can't find a radio example.

**Comment by therealprof** [comment]
No radio example at the moment. There's some radio could which might work on the micro:bit: https://github.com/jonas-schievink/rubble/tree/nrf51

**Comment by therealprof** [comment]
We have a first BLE example now: https://github.com/nrf-rs/microbit/tree/main/examples/ble-beacon so I guess we can close this.
