### ISSUE TITLE
Is there an example on PWM?

### ISSUE THREAD

**Issue by odlg** [nrf-rs/microbit#25]
An example on how to use PWM would be good. I can see at https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v11.0.0%2Flib_pwm.html that it needs a timer, ppi and gpiote, but I can not figure out how to do it.

**Comment by robyoung** [comment]
The speaker example from @blueluna in #59 uses PWM.
