### ISSUE TITLE
RTIC-Example broken

### ISSUE THREAD

**Issue by caemor** [nrf-rs/microbit#73]
The update in https://github.com/nrf-rs/microbit/commit/7c322400213a15c087fbe433306e7c9aaece1b04 broke the non blocking display examples.

I haven't found the time yet to debug which part of the change is causing the issue. But nothing is displayed with the newer version in contrast to the older version where everything works, where the main difference seems to be the clock function.

**Comment by caemor** [comment]
Thanks. This fixes the issue for the nonblocking example for me as well. Do you have an idea how this might apply to the rtic example as well?

**Comment by cathiele** [comment]
> Thanks. This fixes the issue for the nonblocking example for me as well. Do you have an idea how this might apply to the rtic example as well?

In https://github.com/cathiele/microbit/blob/display-rtic-fix/examples/display-rtic/src/main.rs i did a quick hack for fixing it for the V2 board. But this is not a nice solution.

**Comment by caemor** [comment]
Another solution is to modify the Board::take function to steal the Core Peripherals which also isn't the best way to go forward. I am going to ask the RTIC people if there is better solution to this problem.

**Comment by cathiele** [comment]
I think making ```Board::new(p, cp)``` public is the best solution for this.
